name: Compilar APK de SnaptubeLocal

on:
      push:
        branches: [ "main" ]
      workflow_dispatch:

jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Descargar el codigo
            uses: actions/checkout@v4

          - name: Configurar Java
            uses: actions/setup-java@v4
            with:
              distribution: 'zulu'
              java-version: '17'

          - name: Configurar Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.11'

          - name: Instalar Flet
            run: |
              python -m pip install --upgrade pip
              pip install flet yt-dlp

          - name: Compilar APK
            run: yes | flet build apk

          - name: Entregar el APK final
            uses: actions/upload-artifact@v4
            with:
              name: SnaptubeLocal-App
              path: build/apk/**/*.apk
